### ISSUE TITLE
依赖错误(?)

### ISSUE THREAD

**Issue by jht3QAQ** [zfjdhj/mimikkoAutoSignV4#3]
日志如下
```
python3 -m pip install -r requirements.txt 
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting grpcio
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/e7/f9/33e17bb938d4b2afc7373120190e857f951d26f899992a9e717121170e2a/grpcio-1.59.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 25.0 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement yaml (from versions: none)
ERROR: No matching distribution found for yaml
```
以及是否缺少依赖protobuf(?)
```
python3 main.py 
Traceback (most recent call last):
  File "/root/mimikkoAutoSignV4/main.py", line 12, in <module>
    import proto.sign_pb2 as sign_pb2
  File "/root/mimikkoAutoSignV4/proto/sign_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ModuleNotFoundError: No module named 'google'
```

**Comment by zfjdhj** [comment]
依赖文件确实有点问题....
安装这4个应该就行了
grpcio
grpcio-tools
pyyaml
apscheduler
