### ISSUE TITLE
能否出个教程，说明如何获取到authorization？

### ISSUE THREAD

**Issue by angel12538** [zfjdhj/mimikkoAutoSignV4#6]
如题

**Comment by zfjdhj** [comment]
方法1：正常网络抓包，手机端可以使用小黄鸟httpcanary。电脑端可以fiddler配合模拟器。
法2：已root安卓设备，正常登录后，找到目录文件/data/data/com.mimikko.mimikkoui/databases/users.db
打开数据库后users表中的token即为最新auth。
鉴于deviceid只能抓包，还是抓包比较好

**Comment by angel12538** [comment]
感谢大佬，但是今天在运行程序中出现如下报错，请问应该如何解决？
[20231209-09:37:05][line:150][ERROR]:call_api error: code=StatusCode.ABORTED message=阁下当前拥有的能源值不足哦
Traceback (most recent call last):
  File "C:\Users\1\Downloads\mimikkoAutoSignV4-master\main.py", line 438, in <module>
    main(device_id, authorization)
  File "C:\Users\1\Downloads\mimikkoAutoSignV4-master\main.py", line 427, in main
    task_start(device_id, authorization)
  File "C:\Users\1\Downloads\mimikkoAutoSignV4-master\main.py", line 401, in task_start
    task_ordinary_work(client)
  File "C:\Users\1\Downloads\mimikkoAutoSignV4-master\main.py", line 289, in task_ordinary_work
    client.call_api("Work/PickOrdinaryWork",
  File "C:\Users\1\Downloads\mimikkoAutoSignV4-master\main.py", line 159, in call_api
    return res
           ^^^
UnboundLocalError: cannot access local variable 'res' where it is not associated with a value

**Comment by zfjdhj** [comment]
'电力值' 不够继续完成工会任务
暂时可以先手动使用背包里的''能源罐''
等我下次更新修复

**Comment by angel12538** [comment]
好的，感谢

**Comment by angel12538** [comment]
大佬，今天运行程序时出现了新的报错，请问要如何解决？

**Comment by angel12538** [comment]
错误代码如下：
[20231211-22:00:35][line:156][ERROR]:call_api error: code=StatusCode.ABORTED message=兑换物品失败
Traceback (most recent call last):
  File "C:\Users\1\Music\mimikkoAutoSignV4-master\main.py", line 514, in <module>
    main(device_id, authorization)
  File "C:\Users\1\Music\mimikkoAutoSignV4-master\main.py", line 502, in main
    task_start(device_id, authorization)
  File "C:\Users\1\Music\mimikkoAutoSignV4-master\main.py", line 482, in task_start
    task_coin_mall(client)
  File "C:\Users\1\Music\mimikkoAutoSignV4-master\main.py", line 457, in task_coin_mall
    client.call_api("Scalar/Exchange",
  File "C:\Users\1\Music\mimikkoAutoSignV4-master\main.py", line 165, in call_api
    return res
           ^^^
UnboundLocalError: cannot access local variable 'res' where it is not associated with a value
